## 表格输出为图片

In [1]:
import os
os.getcwd()

'C:\\Users\\12602\\Anaconda3\\中指每周模拟下载\\中指数据处理he出图\\2019到2020过渡'

## 整理所需数据

In [3]:
import os
# import pyecharts
import datetime
import pandas as pd
import numpy as np


# 全局  当前周(实际为上周) / 当前月 / 上一个月
currrnt_year = 2021
currentWeek = 1
currentMonth = 1
lastMonth = 12

In [4]:
city_map = {
       "北京": "一二线","上海": "一二线","广州": "一二线","深圳": "一二线","南京": "一二线","苏州": "一二线","厦门": "一二线","合肥": "一二线",
        "天津": "一二线","武汉": "一二线","杭州": "一二线","福州": "一二线","济南": "一二线","南昌": "一二线","无锡": "一二线","宁波": "一二线",
        "成都": "一二线","郑州": "一二线","南宁": "一二线","长沙": "一二线","西安": "一二线","重庆": "一二线","青岛": "一二线","沈阳": "一二线",
        "大连": "一二线","常州": "一二线","徐州": "一二线","南通": "一二线","嘉兴": "三四线","绍兴": "三四线","温州": "一二线","镇江": "三四线",
        "泉州": "一二线","漳州": "三四线","佛山": "一二线","东莞": "一二线","中山": "三四线","惠州": "三四线","珠海": "一二线","安庆": "三四线",
        "株洲": "三四线","阜阳": "三四线","芜湖": "三四线","荆门": "三四线","荆州": "三四线","抚州": "三四线","赣州": "三四线","吉安": "三四线",
        "九江": "三四线","信阳": "三四线","南阳": "三四线","淄博": "三四线","临沂": "三四线","兰州": "一二线","昆明": "一二线","宝鸡": "三四线",
        "德阳": "三四线","哈尔滨": "一二线","湖州": "三四线","江门": "三四线","金华": "三四线","丽水": "三四线","龙岩": "三四线","泸州": "三四线",
        "马鞍山": "三四线","南平": "三四线","内江": "三四线","宁德": "三四线","莆田": "三四线","衢州": "三四线","三明": "三四线","汕头": "三四线",
        "石家庄": "一二线","台州": "三四线","泰州": "三四线","潍坊": "三四线","烟台": "一二线","盐城": "三四线","银川": "一二线","长春": "一二线",
        "肇庆": "三四线","茂名": "三四线","海口": "一二线","泰安": "三四线","威海": "三四线","包头": "三四线","舟山": "三四线","柳州": "三四线",
        "贵港": "三四线","天水": "三四线","淮南": "三四线","玉林": "三四线","牡丹江": "三四线","宣城": "三四线","张家界": "三四线","德州": "三四线",
        "日照": "三四线","淮北": "三四线","广元": "三四线","汉中": "三四线","绵阳": "三四线"}

# 城市类型
cityType = {
    '北京': '深耕型', '上海': '深耕型', '广州': '深耕型', '深圳': '深耕型', '南京': '深耕型', '苏州': '深耕型', '厦门': '深耕型', '合肥': '深耕型', '天津': '深耕型',
    '武汉': '深耕型', '杭州': '深耕型', '福州': '深耕型', '济南': '深耕型', '南昌': '深耕型', '无锡': '据点型', '宁波': '深耕型', '成都': '深耕型', '郑州': '深耕型',
    '南宁': '深耕型', '长沙': '深耕型', '西安': '深耕型', '重庆': '深耕型', '青岛': '深耕型', '沈阳': '深耕型', '大连': '深耕型', '常州': '据点型', '徐州': '深耕型',
    '南通': '据点型', '嘉兴': '据点型', '绍兴': '据点型', '温州': '深耕型', '镇江': '据点型', '泉州': '据点型', '漳州': '据点型', '佛山': '据点型', '东莞': '据点型',
    '中山': '据点型', '惠州': '据点型', '珠海': '深耕型', '安庆': '机会型', '株洲': '机会型', '阜阳': '据点型', '芜湖': '据点型', '荆门': '机会型', '荆州': '机会型',
    '抚州': '机会型', '赣州': '据点型', '吉安': '机会型', '九江': '据点型', '信阳': '机会型', '南阳': '机会型', '淄博': '据点型', '临沂': '据点型', '兰州': '深耕型',
    '昆明': '深耕型', '宝鸡': '机会型', '德阳': '机会型', '哈尔滨': '深耕型', '湖州': '据点型', '江门': '据点型', '金华': '据点型', '丽水': '据点型',
    '龙岩': '据点型', '泸州': '机会型', '马鞍山': '机会型', '南平': '机会型', '内江': '机会型', '宁德': '机会型', '莆田': '据点型', '衢州': '据点型',
    '三明': '机会型', '汕头': '据点型', '石家庄': '深耕型', '台州': '据点型', '泰州': '据点型', '潍坊': '据点型', '烟台': '据点型', '盐城': '据点型',
    '银川': '深耕型', '长春': '深耕型', '肇庆': '机会型', '茂名': '据点型', '海口': '深耕型', '泰安': '据点型', '威海': '据点型', '包头': '据点型', '舟山': '据点型',
    '柳州': '据点型', '贵港': '机会型', '天水': '机会型', '淮南': '机会型', '玉林': '机会型', '牡丹江': '机会型', '宣城': '机会型', '张家界': '机会型',
    '德州': '机会型', '日照': '机会型', '淮北': '机会型', '广元': '机会型', '汉中': '机会型', '绵阳': '机会型'
}

In [5]:
# 底稿城市
city_digao = ['北京', '上海', '广州', '深圳', '南京', '苏州', '厦门', '合肥', '天津', '武汉', '杭州', '福州', '济南', '南昌', 
              '无锡', '宁波', '成都', '郑州', '南宁', '长沙', '西安', '重庆', '青岛', '沈阳', '大连', '常州', '徐州', '南通', 
              '嘉兴', '绍兴', '温州', '镇江', '泉州', '漳州', '佛山', '东莞', '中山', '惠州', '珠海', '安庆', '株洲', '阜阳',
              '芜湖', '荆门', '荆州', '抚州', '赣州', '吉安', '九江', '信阳', '南阳', '淄博', '临沂', '兰州', '昆明', '宝鸡', 
              '德阳', '哈尔滨', '湖州', '江门', '金华', '丽水', '龙岩', '泸州', '马鞍山', '南平', '内江', '宁德', '莆田', '衢州',
              '三明', '汕头', '石家庄', '台州', '泰州', '潍坊', '烟台', '盐城', '银川', '长春', '肇庆', '茂名', '海口', '泰安',
              '威海', '包头', '舟山', '柳州', '贵港', '天水', '淮南', '玉林', '牡丹江', '宣城', '张家界', '德州', '日照',
              '淮北', '广元', '汉中', '绵阳']
# city_digao = pd.DataFrame(city_digao, columns=['城市'])

In [7]:
# 读取数据

deal = pd.read_excel('../数据整理/中指综合后的2016-2020数据.xlsx', sheet_name='土地成交明细')
# deal = deal[deal['周'] != currentWeek+1]
liupai = pd.read_excel('../数据整理/中指综合后的2016-2020数据.xlsx', sheet_name='土地流拍')
# liupai = liupai[liupai['周'] != currentWeek+1]

deal.replace('--', 0, inplace=True)
liupai.replace('--', 0, inplace=True)


deal.loc[deal[deal['起始价(万元)']==0].index, '起始价(万元)'] = deal[deal['起始价(万元)']==0]['成交价(万元)']
deal.loc[deal[deal['成交价(万元)']==0].index, '成交价(万元)'] = deal[deal['成交价(万元)']==0]['起始价(万元)']

deal.fillna(0, inplace=True)
liupai.fillna(0, inplace=True)

In [8]:
# 处理流拍数据
liupai['成交价(万元)'] = 0
liupai['成交楼面价(元/㎡)'] = 0
liupai['溢价率'] = '流拍'
liupai['受让单位'] = ''
liupai['土地星级'] = '0星'
liupai['溢价率分类'] = '流拍'


# 处理成交数据
deal['溢价率分类'] = deal['溢价率'].map(lambda x: '底价' if x<=10 else '高溢价' if x>=50 else '溢价' )

deal_liupai = pd.concat((deal, liupai), ignore_index=True, sort=False)
deal_liupai['日'] = deal_liupai['截止日期'].map(lambda x: str(x.split("-")[2]).lstrip('0'))
deal_liupai['城市能级'] = deal_liupai['城市'].map(lambda x: city_map[x])
deal_liupai['城市分类'] = deal_liupai['城市'].map(lambda x: cityType[x])
# deal_liupai = deal_liupai[deal_liupai['年']==2019]

**需要修改**

In [11]:
# 计算周度指数的时候去除 2019 年 1 月份的数据,
# 计算 第 {} 周的数据
# 方便后边计算2020年本周数据

y = currrnt_year - 1
deal_liupai = deal_liupai.query('年>@y')
deal_liupai = deal_liupai.drop(deal_liupai[(deal_liupai['月'] == currentMonth) & (deal_liupai['年'] == y) ].index)
deal_liupai = deal_liupai.drop(deal_liupai[(deal_liupai['周'] == currentWeek) & (deal_liupai['年'] == y) ].index)
deal_liupai = deal_liupai.drop(deal_liupai[(deal_liupai['月'] == lastMonth) & (deal_liupai['年'] == y) ].index)

deal_liupai.shape

(72, 22)

### 图1 101城溢价率结构表__按周城市出

**计算 101城, 12线, 34线城市 溢价率 **

In [12]:
# TODO
# 本周每个城市溢价率分类详情
d = deal_liupai[deal_liupai['周']==currentWeek]
a = d.pivot_table(values='地块名称', columns='溢价率分类', aggfunc='count',index='城市', fill_value=0)
a.head(2)

溢价率分类  底价  流拍  溢价  高溢价
城市
上海     16   0   0    0
中山      1   0   0    0

In [13]:
# 计算每个城市溢价率   去除 流拍选项
dd = d[d['溢价率分类'] != '流拍']
d1 = dd.pivot_table(values=['起始价(万元)','成交价(万元)'], aggfunc='sum',index='城市', fill_value=0)
d1['溢价率'] = (d1['成交价(万元)'] / d1['起始价(万元)'] - 1) *100
d1 = d1[['溢价率']]

# 计算101城市溢价率
d1.loc['101城'] = (dd['成交价(万元)'].sum() / dd['起始价(万元)'].sum() - 1) *100

# 计算12,和 34 线城市溢价率
d1234 = dd.pivot_table(values=['起始价(万元)','成交价(万元)'], aggfunc='sum',index='城市能级', fill_value=0)
d1234['溢价率'] = (d1234['成交价(万元)'] / d1234['起始价(万元)'] - 1) *100
d1234 = d1234[['溢价率']]
d1234


## 新加1.1  计算 城市类型的溢价率
dType = dd.pivot_table(values=['起始价(万元)','成交价(万元)'], aggfunc='sum',index='城市分类', fill_value=0)
dType['溢价率'] = (dType['成交价(万元)'] / dType['起始价(万元)'] - 1) *100
dType = dType[['溢价率']]
dType

# 合并 全国和12,34线城市
d_all_city = pd.concat((d1, d1234, dType))
d_all_city.replace([np.inf,-np.inf],0, inplace=True)
d_all_city.tail()

            溢价率
一二线   11.550658
三四线   20.478269
据点型   13.676024
机会型  148.532290
深耕型   12.155871

**计算101, 12, 34 城市 成交率**

In [14]:
## 新加1.1 城市类型
dType_city = d.pivot_table(values='地块名称', columns='溢价率分类', aggfunc='count',index='城市分类', fill_value=0)

# 12, 34 线
a12 = d.pivot_table(values='地块名称', columns='溢价率分类', aggfunc='count',index='城市能级', fill_value=0)

# 101城
a101 = d.pivot_table(values='地块名称', columns='溢价率分类', aggfunc='count', fill_value=0)
a101.index = ['101城']
display(dType_city,a101, a12)


# 全国和101,3412城市综合列表
a101_12_34 = pd.concat((a,a12,a101, dType_city))


# 将全国溢价率 合并到全国各个城市中
all_city = pd.concat((a101_12_34,d_all_city), axis=1, sort=True)
all_city.head()

溢价率分类  底价  流拍  溢价  高溢价
城市分类
据点型    13   2   4    3
机会型     1   1   1    1
深耕型    28   0  16    2

溢价率分类  底价  流拍  溢价  高溢价
101城   42   3  21    6

溢价率分类  底价  流拍  溢价  高溢价
城市能级
一二线    31   1  16    2
三四线    11   2   5    4

      底价  流拍  溢价  高溢价        溢价率
101城  42   3  21    6  12.762286
一二线   31   1  16    2  11.550658
三四线   11   2   5    4  20.478269
上海    16   0   0    0   0.245590
中山     1   0   0    0   0.000000

In [15]:
# 101 最终状态, 预留和后边底稿合并
c = all_city.copy()
if '流拍' not in c.columns:
    c['流拍'] = 0
if '高溢价' not in c.columns:
    c['高溢价'] = 0
c.eval(' 总计 = 底价+溢价+高溢价', inplace=True)
c.eval(' 总计流拍 = 底价+溢价+流拍+高溢价', inplace=True)

c['底价成交率'] = (c['底价'] / c['总计']).apply(lambda x: format(x, '.4f')) 
c['流拍率'] = (c['流拍'] / c['总计流拍']).apply(lambda x: format(x, '.4f')) 
# c['溢价'] = (c['溢价'] / c['总计']).apply(lambda x: format(x, '.4f')) 
c['高溢价成交率'] = (c['高溢价'] / c['总计']).apply(lambda x: format(x, '.4f')) 
c = c[['底价成交率', '高溢价成交率', '流拍率','溢价率']]
c.head()

       底价成交率  高溢价成交率     流拍率        溢价率
101城  0.6087  0.0870  0.0417  12.762286
一二线   0.6327  0.0408  0.0200  11.550658
三四线   0.5500  0.2000  0.0909  20.478269
上海    1.0000  0.0000  0.0000   0.245590
中山    1.0000  0.0000  0.0000   0.000000

### 溢价率结构 按照上个月出 （all_city_yue）

In [16]:
# TODO
# 本周每个城市溢价率分类详情
d_yue = deal_liupai[deal_liupai['月']==lastMonth]
a_yue = d_yue.pivot_table(values='地块名称', columns='溢价率分类', aggfunc='count',index='城市', fill_value=0)
a_yue.head()



# 计算每个城市溢价率   去除 流拍选项
dd_yue = d_yue[d_yue['溢价率分类'] !='流拍']
d1_yue = dd_yue.pivot_table(values=['起始价(万元)','成交价(万元)'], aggfunc='sum',index='城市', fill_value=0)
d1_yue['溢价率'] = (d1_yue['成交价(万元)'] / d1_yue['起始价(万元)'] - 1) *100
d1_yue = d1_yue[['溢价率']]

d1_yue.head()



# 计算101城市溢价率
d1_yue.loc['101城'] = (dd_yue['成交价(万元)'].sum() / dd_yue['起始价(万元)'].sum() - 1) *100

# 计算12,和 34 线城市溢价率
d1234_yue = dd_yue.pivot_table(values=['起始价(万元)','成交价(万元)'], aggfunc='sum',index='城市能级', fill_value=0)
d1234_yue['溢价率'] = (d1234_yue['成交价(万元)'] / d1234_yue['起始价(万元)'] - 1) *100
d1234_yue = d1234_yue[['溢价率']]
d1234_yue.head()


## 新加1.1  计算 城市类型的溢价率
dType_yue = dd_yue.pivot_table(values=['起始价(万元)','成交价(万元)'], aggfunc='sum',index='城市分类', fill_value=0)
dType_yue['溢价率'] = (dType_yue['成交价(万元)'] / dType_yue['起始价(万元)'] - 1) *100
dType_yue = dType_yue[['溢价率']]
dType_yue



# 合并 全国和12,34线城市
d_all_city_yue = pd.concat((d1_yue, d1234_yue, dType_yue))
d_all_city_yue.replace([np.inf,-np.inf],0, inplace=True)
d_all_city_yue.head()



## 新加1.1 城市类型
dType_city_yue = d_yue.pivot_table(values='地块名称', columns='溢价率分类', aggfunc='count',index='城市分类', fill_value=0)


# 12, 34 线
a12_yue = d_yue.pivot_table(values='地块名称', columns='溢价率分类', aggfunc='count',index='城市能级', fill_value=0)

# 101线
a101_yue = d_yue.pivot_table(values='地块名称', columns='溢价率分类', aggfunc='count', fill_value=0)
a101_yue.index = ['101城']
display(dType_city_yue, a101_yue, a12_yue)

# 全国和101,3412城市综合列表
a101_12_34_yue = pd.concat((a_yue, a12_yue, a101_yue, dType_city_yue))

# 合并溢价分类, 和 溢价率数据
all_city_yue = pd.concat((a101_12_34_yue, d_all_city_yue), axis=1, sort=True)
all_city_yue.head()

KeyError: '成交价(万元)'

### 溢价率结构,  当前月出  (current_all_city_yue)

In [18]:
# TODO
# 本月每个城市溢价率分类详情
current_d_yue = deal_liupai[deal_liupai['月']==currentMonth]
current_a_yue = current_d_yue.pivot_table(values='地块名称', columns='溢价率分类', aggfunc='count',index='城市', fill_value=0)
# current_a_yue.head()



# 计算每个城市溢价率   去除 流拍选项
current_dd_yue = current_d_yue[current_d_yue['溢价率分类'] !='流拍']
current_d1_yue = current_dd_yue.pivot_table(values=['起始价(万元)','成交价(万元)'], aggfunc='sum',index='城市', fill_value=0)
current_d1_yue['溢价率'] = (current_d1_yue['成交价(万元)'] / current_d1_yue['起始价(万元)'] - 1) *100
current_d1_yue = current_d1_yue[['溢价率']]


# 计算101城市溢价率
current_d1_yue.loc['101城'] = (current_dd_yue['成交价(万元)'].sum() / current_dd_yue['起始价(万元)'].sum() - 1) *100


# # 计算12,和 34 线城市溢价率
current_d1234_yue = current_dd_yue.pivot_table(values=['起始价(万元)','成交价(万元)'], aggfunc='sum',index='城市能级', fill_value=0)
current_d1234_yue['溢价率'] = (current_d1234_yue['成交价(万元)'] / current_d1234_yue['起始价(万元)'] - 1) *100
current_d1234_yue = current_d1234_yue[['溢价率']]
# current_d1234.head()


## 新加1.1  计算 城市类型的溢价率
current_dType_yue = current_dd_yue.pivot_table(values=['起始价(万元)','成交价(万元)'], aggfunc='sum',index='城市分类', fill_value=0)
current_dType_yue['溢价率'] = (current_dType_yue['成交价(万元)'] / current_dType_yue['起始价(万元)'] - 1) *100
current_dType_yue = current_dType_yue[['溢价率']]
current_dType_yue


# # 合并 全国和12,34线城市
current_d_all_city_yue = pd.concat((current_d1_yue, current_d1234_yue,current_dType_yue))
current_d_all_city_yue.replace([np.inf,-np.inf],0, inplace=True)



## 新加1.1 城市类型
current_dType_city_yue = current_d_yue.pivot_table(values='地块名称', columns='溢价率分类', aggfunc='count',index='城市分类', fill_value=0)


# 12, 34 线
current_a12_yue = current_d_yue.pivot_table(values='地块名称', columns='溢价率分类', aggfunc='count',index='城市能级', fill_value=0)

# # 101线
current_a101_yue = current_d_yue.pivot_table(values='地块名称', columns='溢价率分类', aggfunc='count', fill_value=0)
current_a101_yue.index = ['101城']
display(current_a101_yue, current_a12_yue,current_dType_city_yue)



# # 全国和101,3412城市综合列表
current_a101_12_34_yue = pd.concat((current_a_yue, current_a12_yue, current_a101_yue,current_dType_city_yue))
# current_a101_12_34_yue.tail()

# # 合并溢价分类, 和 溢价率数据
current_all_city_yue = pd.concat((current_a101_12_34_yue, current_d_all_city_yue), axis=1, sort=True)
current_all_city_yue.head()

溢价率分类  底价  流拍  溢价  高溢价
101城   42   3  21    6

溢价率分类  底价  流拍  溢价  高溢价
城市能级
一二线    31   1  16    2
三四线    11   2   5    4

溢价率分类  底价  流拍  溢价  高溢价
城市分类
据点型    13   2   4    3
机会型     1   1   1    1
深耕型    28   0  16    2

      底价  流拍  溢价  高溢价        溢价率
101城  42   3  21    6  12.762286
一二线   31   1  16    2  11.550658
三四线   11   2   5    4  20.478269
上海    16   0   0    0   0.245590
中山     1   0   0    0   0.000000

## 房企

In [19]:
enterprise = pd.read_excel('../数据整理/中指综合后的2016-2020数据.xlsx', sheet_name='房企拿地')

enterprise = enterprise[enterprise['周'] != currentWeek+1]

enterprise.fillna(0, inplace=True)
enterprise = enterprise[['房企', '地块名称', '城市', '规划用途', '占地面积(万㎡)',
           '规划建筑面积(万㎡)', '总成交金额(亿元)', '平均楼面价(元/㎡)',
           '平均溢价率(%)', '土地权益(%)','权益金额(亿元)', '权益规划建筑面积(万㎡)', 
            '拿地时间', '城市能级', '年', '月', '周', '房企排名']]
enterprise['城市能级'] = enterprise['城市'].map(lambda x: city_map.get(x, '三四线'))
enterprise['城市分类'] = enterprise['城市'].map(lambda x: cityType.get(x))


enterprise['日'] = enterprise['拿地时间'].map(lambda x: x.split("-")[2].lstrip('0'))
enterprise['溢价率结构'] = enterprise['平均溢价率(%)'].map(lambda x: '溢价率<10%' if x<=10 else '溢价率>50%' if x>=50 else '溢价率10-50%'  )
# enterprise.head(1)

**需要修改**

In [20]:
# 为 方便计算月更, 此处去除2019年一月份数据
# 同时去除第1,2 3周数据
y = currrnt_year - 1
enterprise = enterprise.query('年>@y')
enterprise = enterprise.drop(enterprise[(enterprise['月'] == 1) & (enterprise['年'] == y) ].index)
enterprise = enterprise.drop(enterprise[(enterprise['月'] == currentMonth) & (enterprise['年'] == y) ].index)
enterprise = enterprise.drop(enterprise[(enterprise['周'] == currentWeek) & (enterprise['年'] == y) ].index)
enterprise = enterprise.drop(enterprise[(enterprise['月'] == lastMonth) & (enterprise['年'] == y) ].index)
# enterprise

### 整合成底稿

```
1.房企溢价率为平均溢价率（计算为平均值项）					
2.底价成交率=溢价率<10%地块数量/总计数量					
3.高溢价成交率=溢价率大于50%地块数量/总计数量					
```

#### 底稿 _周度

In [21]:
# TODO
enterpris_week = enterprise[enterprise['周']==currentWeek]
fangqi = enterpris_week.pivot_table(values='地块名称', columns='溢价率结构', aggfunc='count', index='房企排名',fill_value=0)
# fangqi.head()

fangqi.rename(columns={'溢价率10-50%':'溢价', '溢价率<10%':'底价', '溢价率>50%':'高溢价'}, inplace=True)
fangqi['流拍'] = 0


# fangqi.loc['TOP30-50'] = 0
if 'TOP30-50' not in fangqi.index:
    fangqi.loc['TOP30-50'] = 0
if 'TOP30' not in fangqi.index:
    fangqi.loc['TOP30'] = 0

# 合并上边计算出来的 溢价分类数据表
digao = pd.concat((a101_12_34, fangqi), sort=True)
digao = digao.fillna(0)
digao.tail(5)

          底价  流拍  溢价  高溢价
据点型       13   2   4    3
机会型        1   1   1    1
深耕型       28   0  16    2
TOP30      7   0   5    2
TOP30-50   1   0   3    1

In [22]:
digao.columns

Index(['底价', '流拍', '溢价', '高溢价'], dtype='object')

In [23]:
if '高溢价' not in digao.columns:
    digao['高溢价'] = 0

c = digao.copy()
c.eval(' 总计 = 底价+溢价+高溢价', inplace=True)
c.eval(' 总计流拍 = 底价+溢价+流拍+高溢价', inplace=True)

c['底价成交率'] = (c['底价'] / c['总计']).apply(lambda x: format(x, '.4f')) 
c['流拍率'] = (c['流拍'] / c['总计流拍']).apply(lambda x: format(x, '.4f')) 
# c['溢价率'] = (c['溢价'] / c['总计']).apply(lambda x: format(x, '.4f')) 
c['高溢价成交率'] = (c['高溢价'] / c['总计']).apply(lambda x: format(x, '.4f')) 

c1 = c[['底价成交率','流拍率','高溢价成交率']]
c1.replace('nan',0,inplace=True)
c1.tail(2)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:4166: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(

           底价成交率     流拍率  高溢价成交率
TOP30     0.5000  0.0000  0.1429
TOP30-50  0.2000  0.0000  0.2000

In [24]:
# 合并溢价率
all_city = pd.concat((c1, d_all_city), axis=1, sort=True)
all_city.head()

           底价成交率     流拍率  高溢价成交率        溢价率
101城      0.6087  0.0417  0.0870  12.762286
TOP30     0.5000  0.0000  0.1429        NaN
TOP30-50  0.2000  0.0000  0.2000        NaN
一二线       0.6327  0.0200  0.0408  11.550658
三四线       0.5500  0.0909  0.2000  20.478269

In [25]:
# TODO
# 计算TOP30, 和 TOP30-50的溢价率
TOP = enterprise[enterprise['周']==currentWeek]
TOP30 = TOP[TOP["房企排名"] == 'TOP30']
TOP30_50 = TOP[TOP["房企排名"] == "TOP30-50"]

all_city['溢价率'].loc['TOP30'] = TOP30['平均溢价率(%)'].mean()
all_city['溢价率'].loc['TOP30-50'] = TOP30_50['平均溢价率(%)'].mean()
all_city.head()

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

           底价成交率     流拍率  高溢价成交率        溢价率
101城      0.6087  0.0417  0.0870  12.762286
TOP30     0.5000  0.0000  0.1429  23.374601
TOP30-50  0.2000  0.0000  0.2000  39.274276
一二线       0.6327  0.0200  0.0408  11.550658
三四线       0.5500  0.0909  0.2000  20.478269

In [26]:
# 101成
df = pd.DataFrame(['北京', '上海', '广州', '深圳', '南京', '苏州', '厦门', '合肥', '天津', '武汉', '杭州', '福州', '济南', '南昌', '无锡', '宁波', '成都', '郑州', '南宁', '长沙', '西安', '重庆', '青岛', '沈阳', '大连', '常州', '徐州', '南通', '嘉兴', '绍兴', '温州', '镇江', '泉州', '漳州', '佛山', '东莞', '中山', '惠州', '珠海', '安庆', '株洲', '阜阳', '芜湖', '荆门', '荆州', '抚州', '赣州', '吉安', '九江', '信阳', '南阳', '淄博', '临沂', '兰州', '昆明', '宝鸡', '德阳', '哈尔滨', '湖州', '江门', '金华', '丽水', '龙岩', '泸州', '马鞍山', '南平', '内江', '宁德', '莆田', '衢州', '三明', '汕头', '石家庄', '台州', '泰州', '潍坊', '烟台', '盐城', '银川', '长春', '肇庆', '茂名', '海口', '泰安', '威海', '包头', '舟山', '柳州', '贵港', '天水', '淮南', '玉林', '牡丹江', '宣城', '张家界', '德州', '日照', '淮北', '广元', '汉中', '绵阳'])
df.rename(columns={0:'城市'}, inplace=True)
df.set_index('城市', inplace=True)


zuizhong = pd.concat((df, all_city), axis=1, sort=True).fillna(0)
# zuizhong.head()


# 格式化显示
z = zuizhong.astype(float)
for i in z.columns:
    z[i] = z[i].map(lambda x: 0 if isinstance(x, float) and x==0 else '%.4f'%float(x) ) 

zuizhong = z.copy()

if '深耕型' not in zuizhong.index:
    zuizhong.loc['深耕型'] = 0
if '据点型' not in zuizhong.index:
    zuizhong.loc['据点型'] = 0
if '机会型' not in zuizhong.index:
    zuizhong.loc['机会型'] = 0
zuizhong = zuizhong.stack().unstack(0)
zuizhong = zuizhong[['北京', '上海', '广州', '深圳', '南京', '苏州', '厦门', '合肥', '天津', '武汉', '杭州', '福州', '济南', '南昌', '无锡', '宁波', '成都', '郑州', '南宁', '长沙', '西安', '重庆', '青岛', '沈阳', '大连', '常州', '徐州', '南通', '嘉兴', '绍兴', '温州', '镇江', '泉州', '漳州', '佛山', '东莞', '中山', '惠州', '珠海', '安庆', '株洲', '阜阳', '芜湖', '荆门', '荆州', '抚州', '赣州', '吉安', '九江', '信阳', '南阳', '淄博', '临沂', '兰州', '昆明', '宝鸡', '德阳', '哈尔滨', '湖州', '江门', '金华', '丽水', '龙岩', '泸州', '马鞍山', '南平', '内江', '宁德', '莆田', '衢州', '三明', '汕头', '石家庄', '台州', '泰州', '潍坊', '烟台', '盐城', '银川', '长春', '肇庆', '茂名', '海口', '泰安', '威海', '包头', '舟山', '柳州', '贵港', '天水', '淮南', '玉林', '牡丹江', '宣城', '张家界', '德州', '日照', '淮北', '广元', '汉中', '绵阳', "101城", "一二线", "三四线", "TOP30", "TOP30-50", '深耕型','据点型','机会型']]
zuizhong = zuizhong.loc[['溢价率', '底价成交率', '高溢价成交率', '流拍率']]
# zuizhong = zuizhong.replace(0, np.NaN)
for i in zuizhong.columns:
    if len([i for i in zuizhong[i].tolist() if i==0])==4:
        zuizhong[i] = zuizhong[i].replace(0, np.NaN)
zuizhong

,北京,上海,广州,深圳,南京,苏州,厦门,合肥,天津,武汉,...,汉中,绵阳,101城,一二线,三四线,TOP30,TOP30-50,深耕型,据点型,机会型
溢价率,NaN,0.2456,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,12.7623,11.5507,20.4783,23.3746,39.2743,12.1559,13.6760,148.5323
底价成交率,NaN,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.6087,0.6327,0.5500,0.5000,0.2000,0.6087,0.6500,0.3333
高溢价成交率,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0870,0.0408,0.2000,0.1429,0.2000,0.0435,0.1500,0.3333
流拍率,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0417,0.0200,0.0909,0,0,0,0.0909,0.2500

#### 底稿 _上月度

In [27]:
# TODO
enterprise_yue = enterprise[enterprise['月']==lastMonth]
fangqi_yue = enterprise_yue.pivot_table(values='地块名称', columns='溢价率结构', aggfunc='count', index='房企排名',fill_value=0)
# fangqi.head()

fangqi_yue.rename(columns={'溢价率10-50%':'溢价', '溢价率<10%':'底价', '溢价率>50%':'高溢价'}, inplace=True)
fangqi_yue['流拍'] = 0


# 合并上边计算出来的 溢价分类数据表
digao_yue = pd.concat((a101_12_34_yue, fangqi_yue), sort=True)
digao_yue = digao_yue.fillna(0)
digao_yue.head(1)

NameError: name 'a101_12_34_yue' is not defined

In [28]:
c = digao_yue.copy()
c.eval(' 总计 = 底价+溢价+高溢价', inplace=True)
c.eval(' 总计流拍 = 底价+溢价+流拍+高溢价', inplace=True)

c['底价成交率'] = (c['底价'] / c['总计']).apply(lambda x: format(x, '.4f')) 
c['流拍率'] = (c['流拍'] / c['总计流拍']).apply(lambda x: format(x, '.4f')) 
c['高溢价成交率'] = (c['高溢价'] / c['总计']).apply(lambda x: format(x, '.4f')) 

c1 = c[['底价成交率','流拍率','高溢价成交率']]
c1.replace('nan',0,inplace=True)
c1.tail(2)

NameError: name 'digao_yue' is not defined

In [29]:
# 合并溢价率
all_city_yue = pd.concat((c1, d_all_city_yue), axis=1, sort=True)
# all_city_yue

NameError: name 'd_all_city_yue' is not defined

In [30]:
# TODO
# 计算TOP30, 和 TOP30-50的溢价率
TOP = enterprise[enterprise['月']==lastMonth]
TOP30 = TOP[TOP["房企排名"] == 'TOP30']
TOP30_50 = TOP[TOP["房企排名"] == "TOP30-50"]

all_city_yue['溢价率'].loc['TOP30'] = TOP30['平均溢价率(%)'].mean() 
all_city_yue['溢价率'].loc['TOP30-50'] = TOP30_50['平均溢价率(%)'].mean()
all_city_yue.head()

NameError: name 'all_city_yue' is not defined

In [31]:
# 101成
df = pd.DataFrame(['北京', '上海', '广州', '深圳', '南京', '苏州', '厦门', '合肥', '天津', '武汉', '杭州', '福州', '济南', '南昌', '无锡', '宁波', '成都', '郑州', '南宁', '长沙', '西安', '重庆', '青岛', '沈阳', '大连', '常州', '徐州', '南通', '嘉兴', '绍兴', '温州', '镇江', '泉州', '漳州', '佛山', '东莞', '中山', '惠州', '珠海', '安庆', '株洲', '阜阳', '芜湖', '荆门', '荆州', '抚州', '赣州', '吉安', '九江', '信阳', '南阳', '淄博', '临沂', '兰州', '昆明', '宝鸡', '德阳', '哈尔滨', '湖州', '江门', '金华', '丽水', '龙岩', '泸州', '马鞍山', '南平', '内江', '宁德', '莆田', '衢州', '三明', '汕头', '石家庄', '台州', '泰州', '潍坊', '烟台', '盐城', '银川', '长春', '肇庆', '茂名', '海口', '泰安', '威海', '包头', '舟山', '柳州', '贵港', '天水', '淮南', '玉林', '牡丹江', '宣城', '张家界', '德州', '日照', '淮北', '广元', '汉中', '绵阳'])
df.rename(columns={0:'城市'}, inplace=True)
df.set_index('城市', inplace=True)


zuizhong_yue = pd.concat((df, all_city_yue), axis=1, sort=True).fillna(0)



# 格式化显示
z = zuizhong_yue.astype(float)
for i in z.columns:
    z[i] = z[i].map(lambda x: 0 if isinstance(x, float) and x==0 else '%.4f'%float(x) ) 

zuizhong_yue = z.copy()
if '深耕型' not in zuizhong_yue.index:
    zuizhong_yue.loc['深耕型'] = 0
if '据点型' not in zuizhong_yue.index:
    zuizhong_yue.loc['据点型'] = 0
if '机会型' not in zuizhong_yue.index:
    zuizhong_yue.loc['机会型'] = 0
zuizhong_yue = zuizhong_yue.stack().unstack(0)
zuizhong_yue = zuizhong_yue[['北京', '上海', '广州', '深圳', '南京', '苏州', '厦门', '合肥', '天津', '武汉', '杭州', '福州', '济南', '南昌', '无锡', '宁波', '成都', '郑州', '南宁', '长沙', '西安', '重庆', '青岛', '沈阳', '大连', '常州', '徐州', '南通', '嘉兴', '绍兴', '温州', '镇江', '泉州', '漳州', '佛山', '东莞', '中山', '惠州', '珠海', '安庆', '株洲', '阜阳', '芜湖', '荆门', '荆州', '抚州', '赣州', '吉安', '九江', '信阳', '南阳', '淄博', '临沂', '兰州', '昆明', '宝鸡', '德阳', '哈尔滨', '湖州', '江门', '金华', '丽水', '龙岩', '泸州', '马鞍山', '南平', '内江', '宁德', '莆田', '衢州', '三明', '汕头', '石家庄', '台州', '泰州', '潍坊', '烟台', '盐城', '银川', '长春', '肇庆', '茂名', '海口', '泰安', '威海', '包头', '舟山', '柳州', '贵港', '天水', '淮南', '玉林', '牡丹江', '宣城', '张家界', '德州', '日照', '淮北', '广元', '汉中', '绵阳', "101城", "一二线", "三四线", "TOP30", "TOP30-50", '深耕型','据点型','机会型']]
zuizhong_yue = zuizhong_yue.loc[['溢价率', '底价成交率', '高溢价成交率', '流拍率']]
# zuizhong_yue = zuizhong_yue.replace(0, np.NaN)
for i in zuizhong_yue.columns:
    if len([i for i in zuizhong_yue[i].tolist() if i==0])==4:
        zuizhong_yue[i] = zuizhong_yue[i].replace(0, np.NaN)
zuizhong_yue

NameError: name 'all_city_yue' is not defined

#### 底稿_当前月

In [32]:
# # TODO
current_enterprise_yue = enterprise[enterprise['月']==currentMonth]
current_fangqi_yue = current_enterprise_yue.pivot_table(values='地块名称', columns='溢价率结构', aggfunc='count', index='房企排名',fill_value=0)

# 不存在某些字段, 则添加上
for i in ['溢价率10-50%', '溢价率<10%','溢价率>50%']:
    if i not in current_fangqi_yue.columns:
        current_fangqi_yue[i] = 0
    

current_fangqi_yue.rename(columns={'溢价率10-50%':'溢价', '溢价率<10%':'底价', '溢价率>50%':'高溢价'}, inplace=True)
current_fangqi_yue['流拍'] = 0
current_fangqi_yue


# # 合并上边计算出来的 溢价分类数据表
current_digao_yue = pd.concat((current_a101_12_34_yue, current_fangqi_yue), sort=True)
current_digao_yue = current_digao_yue.fillna(0)

if "TOP30-50" not in current_digao_yue.index:
    current_digao_yue.loc['TOP30-50'] = [0, 0, 0, 0]
if "TOP30" not in current_digao_yue.index:
    current_digao_yue.loc['TOP30'] = [0, 0, 0, 0]
current_digao_yue.tail(2)

          底价  流拍  溢价  高溢价
TOP30      7   0   5    2
TOP30-50   1   0   3    1

In [33]:
c = current_digao_yue.copy()
c.eval(' 总计 = 底价+溢价+高溢价', inplace=True)
c.eval(' 总计流拍 = 底价+溢价+流拍+高溢价', inplace=True)

c['底价成交率'] = (c['底价'] / c['总计']).apply(lambda x: format(x, '.4f')) 
c['流拍率'] = (c['流拍'] / c['总计流拍']).apply(lambda x: format(x, '.4f')) 
c['高溢价成交率'] = (c['高溢价'] / c['总计']).apply(lambda x: format(x, '.4f')) 

c1 = c[['底价成交率','流拍率','高溢价成交率']]
c1.replace('nan',0,inplace=True)
c1.tail(2)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:4166: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(

           底价成交率     流拍率  高溢价成交率
TOP30     0.5000  0.0000  0.1429
TOP30-50  0.2000  0.0000  0.2000

In [34]:
# # 合并溢价率
current_all_city_yue = pd.concat((c1, current_d_all_city_yue), axis=1, sort=True)
current_all_city_yue.head()

           底价成交率     流拍率  高溢价成交率        溢价率
101城      0.6087  0.0417  0.0870  12.762286
TOP30     0.5000  0.0000  0.1429        NaN
TOP30-50  0.2000  0.0000  0.2000        NaN
一二线       0.6327  0.0200  0.0408  11.550658
三四线       0.5500  0.0909  0.2000  20.478269

In [35]:
# # TODO
# 计算TOP30, 和 TOP30-50的溢价率
current_TOP = enterprise[enterprise['月']==currentMonth]
current_TOP30 = current_TOP[current_TOP["房企排名"] == 'TOP30']
current_TOP30_50 = current_TOP[current_TOP["房企排名"] == "TOP30-50"]

current_all_city_yue['溢价率'].loc['TOP30'] = 0 if len(current_TOP30)==0 else current_TOP30['平均溢价率(%)'].mean() 
current_all_city_yue['溢价率'].loc['TOP30-50'] = 0 if len(current_TOP30_50)==0 else current_TOP30_50['平均溢价率(%)'].mean()

current_all_city_yue.head()

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

           底价成交率     流拍率  高溢价成交率        溢价率
101城      0.6087  0.0417  0.0870  12.762286
TOP30     0.5000  0.0000  0.1429  23.374601
TOP30-50  0.2000  0.0000  0.2000  39.274276
一二线       0.6327  0.0200  0.0408  11.550658
三四线       0.5500  0.0909  0.2000  20.478269

In [36]:
city_map.keys()

dict_keys(['北京', '上海', '广州', '深圳', '南京', '苏州', '厦门', '合肥', '天津', '武汉', '杭州', '福州', '济南', '南昌', '无锡', '宁波', '成都', '郑州', '南宁', '长沙', '西安', '重庆', '青岛', '沈阳', '大连', '常州', '徐州', '南通', '嘉兴', '绍兴', '温州', '镇江', '泉州', '漳州', '佛山', '东莞', '中山', '惠州', '珠海', '安庆', '株洲', '阜阳', '芜湖', '荆门', '荆州', '抚州', '赣州', '吉安', '九江', '信阳', '南阳', '淄博', '临沂', '兰州', '昆明', '宝鸡', '德阳', '哈尔滨', '湖州', '江门', '金华', '丽水', '龙岩', '泸州', '马鞍山', '南平', '内江', '宁德', '莆田', '衢州', '三明', '汕头', '石家庄', '台州', '泰州', '潍坊', '烟台', '盐城', '银川', '长春', '肇庆', '茂名', '海口', '泰安', '威海', '包头', '舟山', '柳州', '贵港', '天水', '淮南', '玉林', '牡丹江', '宣城', '张家界', '德州', '日照', '淮北', '广元', '汉中', '绵阳'])

In [37]:
# 101成
current_df = pd.DataFrame(['北京', '上海', '广州', '深圳', '南京', '苏州', '厦门', '合肥', '天津', '武汉', '杭州', '福州', '济南', '南昌', '无锡', '宁波', '成都', '郑州', '南宁', '长沙', '西安', '重庆', '青岛', '沈阳', '大连', '常州', '徐州', '南通', '嘉兴', '绍兴', '温州', '镇江', '泉州', '漳州', '佛山', '东莞', '中山', '惠州', '珠海', '安庆', '株洲', '阜阳', '芜湖', '荆门', '荆州', '抚州', '赣州', '吉安', '九江', '信阳', '南阳', '淄博', '临沂', '兰州', '昆明', '宝鸡', '德阳', '哈尔滨', '湖州', '江门', '金华', '丽水', '龙岩', '泸州', '马鞍山', '南平', '内江', '宁德', '莆田', '衢州', '三明', '汕头', '石家庄', '台州', '泰州', '潍坊', '烟台', '盐城', '银川', '长春', '肇庆', '茂名', '海口', '泰安', '威海', '包头', '舟山', '柳州', '贵港', '天水', '淮南', '玉林', '牡丹江', '宣城', '张家界', '德州', '日照', '淮北', '广元', '汉中', '绵阳'])
current_df.rename(columns={0:'城市'}, inplace=True)
current_df.set_index('城市', inplace=True)


current_zuizhong_yue = pd.concat((current_df, current_all_city_yue), axis=1, sort=True).fillna(0)


# # 格式化显示
z = current_zuizhong_yue.astype(float)
for i in z.columns:
    z[i] = z[i].map(lambda x: 0 if isinstance(x, float) and x==0 else '%.4f'%float(x) ) 

current_zuizhong_yue = z.copy()
if '深耕型' not in current_zuizhong_yue.index:
    current_zuizhong_yue.loc['深耕型'] = 0
if '据点型' not in current_zuizhong_yue.index:
    current_zuizhong_yue.loc['据点型'] = 0
if '机会型' not in current_zuizhong_yue.index:
    current_zuizhong_yue.loc['机会型'] = 0
current_zuizhong_yue = current_zuizhong_yue.stack().unstack(0)
current_zuizhong_yue = current_zuizhong_yue[['北京', '上海', '广州', '深圳', '南京', '苏州', '厦门', '合肥', '天津', '武汉', '杭州', '福州', '济南', '南昌', '无锡', '宁波', '成都', '郑州', '南宁', '长沙', '西安', '重庆', '青岛', '沈阳', '大连', '常州', '徐州', '南通', '嘉兴', '绍兴', '温州', '镇江', '泉州', '漳州', '佛山', '东莞', '中山', '惠州', '珠海', '安庆', '株洲', '阜阳', '芜湖', '荆门', '荆州', '抚州', '赣州', '吉安', '九江', '信阳', '南阳', '淄博', '临沂', '兰州', '昆明', '宝鸡', '德阳', '哈尔滨', '湖州', '江门', '金华', '丽水', '龙岩', '泸州', '马鞍山', '南平', '内江', '宁德', '莆田', '衢州', '三明', '汕头', '石家庄', '台州', '泰州', '潍坊', '烟台', '盐城', '银川', '长春', '肇庆', '茂名', '海口', '泰安', '威海', '包头', '舟山', '柳州', '贵港', '天水', '淮南', '玉林', '牡丹江', '宣城', '张家界', '德州', '日照', '淮北', '广元', '汉中', '绵阳', "101城",  "一二线", "三四线", "TOP30", "TOP30-50",'深耕型','据点型','机会型']]
current_zuizhong_yue = current_zuizhong_yue.loc[['溢价率', '底价成交率', '高溢价成交率', '流拍率']]
# current_zuizhong_yue = current_zuizhong_yue.replace(0, np.NaN)
for i in current_zuizhong_yue.columns:
    if len([i for i in current_zuizhong_yue[i].tolist() if i==0])==4:
        current_zuizhong_yue[i] = current_zuizhong_yue[i].replace(0, np.NaN)
current_zuizhong_yue

,北京,上海,广州,深圳,南京,苏州,厦门,合肥,天津,武汉,...,汉中,绵阳,101城,一二线,三四线,TOP30,TOP30-50,深耕型,据点型,机会型
溢价率,NaN,0.2456,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,12.7623,11.5507,20.4783,23.3746,39.2743,12.1559,13.6760,148.5323
底价成交率,NaN,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.6087,0.6327,0.5500,0.5000,0.2000,0.6087,0.6500,0.3333
高溢价成交率,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0870,0.0408,0.2000,0.1429,0.2000,0.0435,0.1500,0.3333
流拍率,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0417,0.0200,0.0909,0,0,0,0.0909,0.2500

#### 保存预警指标

In [38]:
# datetime.datetime.now().isocalendar()[1]-1  周
name = "../数据整理/世茂指标预警_{}周.xlsx".format(currentWeek)
writer = pd.ExcelWriter(name)

zuizhong_one = zuizhong.copy()
for i in zuizhong_one.columns: 
    zuizhong_one[i] = zuizhong_one[i].map(lambda x: int(x) if x in [0, 1] else float(x))

current_zuizhong_yue_one = current_zuizhong_yue.copy()
for i in current_zuizhong_yue_one.columns: 
    current_zuizhong_yue_one[i] = current_zuizhong_yue_one[i].map(lambda x: int(x) if x in [0, 1] else float(x))

    
# 当前月是12月, 有问题,要注销
# zuizhong_yue_one = zuizhong_yue.copy()
# for i in zuizhong_yue_one.columns: 
#     zuizhong_yue_one[i] = zuizhong_yue_one[i].map(lambda x: int(x) if x in [0, 1] else float(x))

NameError: name 'zuizhong_yue' is not defined

In [40]:
zuizhong_one.to_excel(writer, sheet_name='土地预警指标_周更')
current_zuizhong_yue_one.to_excel(writer, sheet_name='土地预警指标_%s月更'%currentMonth)
# zuizhong_yue_one.to_excel(writer, sheet_name='土地预警指标_%s月更'%lastMonth)   # 当前月是12月, 有问题,要注销
writer.save()
writer.close()

## 11, 国庆的时候用的, 其他时间直接删除, 这里时间跨度为2周

In [ ]:
# # 计算周度指数的时候去除 2019 年 1 月份的数据,
# # 计算 第 {} 周的数据
# # 方便后边计算2020年本周数据

# deal_liupai = deal_liupai[deal_liupai['年'] == 2020]
# deal_liupai = deal_liupai[deal_liupai['周'].isin([40,41])]
# deal_liupai

In [ ]:
# # TODO
# # 本周每个城市溢价率分类详情
# d = deal_liupai.copy()
# a = d.pivot_table(values='地块名称', columns='溢价率分类', aggfunc='count',index='城市', fill_value=0)
# a.head(2)


# # 计算每个城市溢价率   去除 流拍选项
# dd = d[d['溢价率分类'] != '流拍']
# d1 = dd.pivot_table(values=['起始价(万元)','成交价(万元)'], aggfunc='sum',index='城市', fill_value=0)
# d1['溢价率'] = (d1['成交价(万元)'] / d1['起始价(万元)'] - 1) *100
# d1 = d1[['溢价率']]

# # 计算101城市溢价率
# d1.loc['101城'] = (dd['成交价(万元)'].sum() / dd['起始价(万元)'].sum() - 1) *100

# # 计算12,和 34 线城市溢价率
# d1234 = dd.pivot_table(values=['起始价(万元)','成交价(万元)'], aggfunc='sum',index='城市能级', fill_value=0)
# d1234['溢价率'] = (d1234['成交价(万元)'] / d1234['起始价(万元)'] - 1) *100
# d1234 = d1234[['溢价率']]
# d1234


# ## 新加1.1  计算 城市类型的溢价率
# dType = dd.pivot_table(values=['起始价(万元)','成交价(万元)'], aggfunc='sum',index='城市分类', fill_value=0)
# dType['溢价率'] = (dType['成交价(万元)'] / dType['起始价(万元)'] - 1) *100
# dType = dType[['溢价率']]
# dType

# # 合并 全国和12,34线城市
# d_all_city = pd.concat((d1, d1234, dType))
# d_all_city.replace([np.inf,-np.inf],0, inplace=True)
# d_all_city.tail()

In [ ]:
# ## 新加1.1 城市类型
# dType_city = d.pivot_table(values='地块名称', columns='溢价率分类', aggfunc='count',index='城市分类', fill_value=0)

# # 12, 34 线
# a12 = d.pivot_table(values='地块名称', columns='溢价率分类', aggfunc='count',index='城市能级', fill_value=0)

# # 101城
# a101 = d.pivot_table(values='地块名称', columns='溢价率分类', aggfunc='count', fill_value=0)
# a101.index = ['101城']
# display(dType_city,a101, a12)


# # 全国和101,3412城市综合列表
# a101_12_34 = pd.concat((a,a12,a101, dType_city))


# # 将全国溢价率 合并到全国各个城市中
# all_city = pd.concat((a101_12_34,d_all_city), axis=1, sort=True)
# all_city.head()

In [ ]:
# # 101 最终状态, 预留和后边底稿合并
# c = all_city.copy()
# if '流拍' not in c.columns:
#     c['流拍'] = 0
# if '高溢价' not in c.columns:
#     c['高溢价'] = 0
# c.eval(' 总计 = 底价+溢价+高溢价', inplace=True)
# c.eval(' 总计流拍 = 底价+溢价+流拍+高溢价', inplace=True)

# c['底价成交率'] = (c['底价'] / c['总计']).apply(lambda x: format(x, '.4f')) 
# c['流拍率'] = (c['流拍'] / c['总计流拍']).apply(lambda x: format(x, '.4f')) 
# # c['溢价'] = (c['溢价'] / c['总计']).apply(lambda x: format(x, '.4f')) 
# c['高溢价成交率'] = (c['高溢价'] / c['总计']).apply(lambda x: format(x, '.4f')) 
# c = c[['底价成交率', '高溢价成交率', '流拍率','溢价率']]
# c.head()

### 房企

In [ ]:
# enterprise = pd.read_excel('../数据整理/中指综合后的2016-2020数据.xlsx', sheet_name='房企拿地')

# # enterprise = enterprise[enterprise['周'] != currentWeek+1]
# enterprise = enterprise[enterprise['年'] == 2020]
# enterprise = enterprise[enterprise['周'].isin([40,41])]

# enterprise.fillna(0, inplace=True)
# enterprise = enterprise[['房企', '地块名称', '城市', '规划用途', '占地面积(万㎡)',
#            '规划建筑面积(万㎡)', '总成交金额(亿元)', '平均楼面价(元/㎡)',
#            '平均溢价率(%)', '土地权益(%)','权益金额(亿元)', '权益规划建筑面积(万㎡)', 
#             '拿地时间', '城市能级', '年', '月', '周', '房企排名']]
# enterprise['城市能级'] = enterprise['城市'].map(lambda x: city_map.get(x, '三四线'))
# enterprise['城市分类'] = enterprise['城市'].map(lambda x: cityType.get(x))


# enterprise['日'] = enterprise['拿地时间'].map(lambda x: x.split("-")[2].lstrip('0'))
# enterprise['溢价率结构'] = enterprise['平均溢价率(%)'].map(lambda x: '溢价率<10%' if x<=10 else '溢价率>50%' if x>=50 else '溢价率10-50%'  )
# # enterprise.head(1)

In [ ]:
# # TODO
# enterpris_week = enterprise.copy()
# fangqi = enterpris_week.pivot_table(values='地块名称', columns='溢价率结构', aggfunc='count', index='房企排名',fill_value=0)
# # fangqi.head()

# fangqi.rename(columns={'溢价率10-50%':'溢价', '溢价率<10%':'底价', '溢价率>50%':'高溢价'}, inplace=True)
# fangqi['流拍'] = 0


# # fangqi.loc['TOP30-50'] = 0
# if 'TOP30-50' not in fangqi.index:
#     fangqi.loc['TOP30-50'] = 0
# if 'TOP30' not in fangqi.index:
#     fangqi.loc['TOP30'] = 0

# # 合并上边计算出来的 溢价分类数据表
# digao = pd.concat((a101_12_34, fangqi), sort=True)
# digao = digao.fillna(0)
# digao.tail(5)

In [ ]:
# if '高溢价' not in digao.columns:
#     digao['高溢价'] = 0

# c = digao.copy()
# c.eval(' 总计 = 底价+溢价+高溢价', inplace=True)
# c.eval(' 总计流拍 = 底价+溢价+流拍+高溢价', inplace=True)

# c['底价成交率'] = (c['底价'] / c['总计']).apply(lambda x: format(x, '.4f')) 
# c['流拍率'] = (c['流拍'] / c['总计流拍']).apply(lambda x: format(x, '.4f')) 
# # c['溢价率'] = (c['溢价'] / c['总计']).apply(lambda x: format(x, '.4f')) 
# c['高溢价成交率'] = (c['高溢价'] / c['总计']).apply(lambda x: format(x, '.4f')) 

# c1 = c[['底价成交率','流拍率','高溢价成交率']]
# c1.replace('nan',0,inplace=True)
# c1.tail(2)

In [ ]:
# # 合并溢价率
# all_city = pd.concat((c1, d_all_city), axis=1, sort=True)
# all_city.head()

In [ ]:
# # TODO
# # 计算TOP30, 和 TOP30-50的溢价率
# TOP = enterprise[enterprise['周']==currentWeek]
# TOP30 = TOP[TOP["房企排名"] == 'TOP30']
# TOP30_50 = TOP[TOP["房企排名"] == "TOP30-50"]

# all_city['溢价率'].loc['TOP30'] = TOP30['平均溢价率(%)'].mean()
# all_city['溢价率'].loc['TOP30-50'] = TOP30_50['平均溢价率(%)'].mean()
# all_city.head()

In [ ]:
# # 101成
# df = pd.DataFrame(['北京', '上海', '广州', '深圳', '南京', '苏州', '厦门', '合肥', '天津', '武汉', '杭州', '福州', '济南', '南昌', '无锡', '宁波', '成都', '郑州', '南宁', '长沙', '西安', '重庆', '青岛', '沈阳', '大连', '常州', '徐州', '南通', '嘉兴', '绍兴', '温州', '镇江', '泉州', '漳州', '佛山', '东莞', '中山', '惠州', '珠海', '安庆', '株洲', '阜阳', '芜湖', '荆门', '荆州', '抚州', '赣州', '吉安', '九江', '信阳', '南阳', '淄博', '临沂', '兰州', '昆明', '宝鸡', '德阳', '哈尔滨', '湖州', '江门', '金华', '丽水', '龙岩', '泸州', '马鞍山', '南平', '内江', '宁德', '莆田', '衢州', '三明', '汕头', '石家庄', '台州', '泰州', '潍坊', '烟台', '盐城', '银川', '长春', '肇庆', '茂名', '海口', '泰安', '威海', '包头', '舟山', '柳州', '贵港', '天水', '淮南', '玉林', '牡丹江', '宣城', '张家界', '德州', '日照', '淮北', '广元', '汉中', '绵阳'])
# df.rename(columns={0:'城市'}, inplace=True)
# df.set_index('城市', inplace=True)


# zuizhong = pd.concat((df, all_city), axis=1, sort=True).fillna(0)
# # zuizhong.head()


# # 格式化显示
# z = zuizhong.astype(float)
# for i in z.columns:
#     z[i] = z[i].map(lambda x: 0 if isinstance(x, float) and x==0 else '%.4f'%float(x) ) 

# zuizhong = z.copy()

# if '深耕型' not in zuizhong.index:
#     zuizhong.loc['深耕型'] = 0
# if '据点型' not in zuizhong.index:
#     zuizhong.loc['据点型'] = 0
# if '机会型' not in zuizhong.index:
#     zuizhong.loc['机会型'] = 0
# zuizhong = zuizhong.stack().unstack(0)
# zuizhong = zuizhong[['北京', '上海', '广州', '深圳', '南京', '苏州', '厦门', '合肥', '天津', '武汉', '杭州', '福州', '济南', '南昌', '无锡', '宁波', '成都', '郑州', '南宁', '长沙', '西安', '重庆', '青岛', '沈阳', '大连', '常州', '徐州', '南通', '嘉兴', '绍兴', '温州', '镇江', '泉州', '漳州', '佛山', '东莞', '中山', '惠州', '珠海', '安庆', '株洲', '阜阳', '芜湖', '荆门', '荆州', '抚州', '赣州', '吉安', '九江', '信阳', '南阳', '淄博', '临沂', '兰州', '昆明', '宝鸡', '德阳', '哈尔滨', '湖州', '江门', '金华', '丽水', '龙岩', '泸州', '马鞍山', '南平', '内江', '宁德', '莆田', '衢州', '三明', '汕头', '石家庄', '台州', '泰州', '潍坊', '烟台', '盐城', '银川', '长春', '肇庆', '茂名', '海口', '泰安', '威海', '包头', '舟山', '柳州', '贵港', '天水', '淮南', '玉林', '牡丹江', '宣城', '张家界', '德州', '日照', '淮北', '广元', '汉中', '绵阳', "101城", "一二线", "三四线", "TOP30", "TOP30-50", '深耕型','据点型','机会型']]
# zuizhong = zuizhong.loc[['溢价率', '底价成交率', '高溢价成交率', '流拍率']]
# # zuizhong = zuizhong.replace(0, np.NaN)
# for i in zuizhong.columns:
#     if len([i for i in zuizhong[i].tolist() if i==0])==4:
#         zuizhong[i] = zuizhong[i].replace(0, np.NaN)
# zuizhong

In [ ]:
# # datetime.datetime.now().isocalendar()[1]-1  周
# name = "../数据整理/{}周.xlsx".format(currentWeek)
# writer = pd.ExcelWriter(name)

# zuizhong_one = zuizhong.copy()
# for i in zuizhong_one.columns: 
#     zuizhong_one[i] = zuizhong_one[i].map(lambda x: int(x) if x in [0, 1] else float(x))

In [ ]:
# zuizhong_one.to_excel(writer, sheet_name='土地预警指标_周更')
# writer.save()
# writer.close()